const prefix = "schoolIntranet.v1";

export const storageKeys = {
  users: `${prefix}.users`,
  credentials: `${prefix}.credentials`,
  students: `${prefix}.students`,
  courses: `${prefix}.courses`,
  enrollments: `${prefix}.enrollments`,
  grades: `${prefix}.grades`,
  attendance: `${prefix}.attendance`,
  announcements: `${prefix}.announcements`,
  profiles: `${prefix}.profiles`,
  avatars: `${prefix}.avatars`,
  accessibility: `${prefix}.accessibility`,
  timelineEvents: `${prefix}.timelineEvents`,
  achievements: `${prefix}.achievements`,
  forumPosts: `${prefix}.forumPosts`,
  forumComments: `${prefix}.forumComments`,
  incidents: `${prefix}.incidents`,
  campusLocations: `${prefix}.campusLocations`,
  emergencyNotices: `${prefix}.emergencyNotices`,
  buses: `${prefix}.buses`,
  busRoutes: `${prefix}.busRoutes`,
  cafeteriaProducts: `${prefix}.cafeteriaProducts`,
  scheduleEntries: `${prefix}.scheduleEntries`,
  notifications: `${prefix}.notifications`,
  session: `${prefix}.session`,
} as const;
