import {notify} from '../notifications/service';import type {UserRole} from '../../core/types';
export type Category='General'|'Académico'|'Deportes'|'Tecnología'|'Actividades'|'Clubes'|'Ayuda';
export interface Comment{id:string;authorId:string;authorName:string;body:string;createdAt:string;parentId?:string;hidden:boolean;}
export interface Post{id:string;authorId:string;authorName:string;title:string;body:string;category:Category;createdAt:string;reactions:number;reported:boolean;hidden:boolean;closed:boolean;comments:Comment[];}
const KEY='campus-operations.forum.v1';export const categories:Category[]=['General','Académico','Deportes','Tecnología','Actividades','Clubes','Ayuda'];
export const demoData:Post[]=Array.from({length:7},(_,i)=>({id:`post-${i+1}`,authorId:i===0?'usr_admin_001':`usr_demo_${i+1}`,authorName:['Elena Mora','Carlos Vega','Ana Solís','Luis Rojas','María León','Jorge Mora','Sofía Cruz'][i],title:['Bienvenidos al foro escolar','Consejos para estudiar ciencias','Entrenamiento para la carrera','Club de tecnología','Ideas para la feria escolar','Club de lectura','Necesito ayuda con una actividad'][i],body:['Espacio para conversar y colaborar con respeto.','¿Qué técnicas les funcionan para preparar un examen?','Compartamos rutinas y recomendaciones para prepararnos.','Propongamos proyectos que puedan desarrollar los clubes.','¿Qué actividad les gustaría ver este trimestre?','Recomendemos libros apropiados para la comunidad.','¿Alguien puede explicar este tema?'][i],category:categories[i],createdAt:new Date(Date.now()-(i+1)*3600000).toISOString(),reactions:3+i,reported:false,hidden:false,closed:false,comments:[{id:`comment-${i+1}`,authorId:'usr_admin_001',authorName:'Elena Mora',body:'Gracias por compartir.',createdAt:new Date(Date.now()-(i+1)*1800000).toISOString(),hidden:false}]}));
export function list(){try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw) as Post[]:demoData;}catch{return demoData;}}export function seed(){if(!localStorage.getItem(KEY))localStorage.setItem(KEY,JSON.stringify(demoData));}export function save(items:Post[]){localStorage.setItem(KEY,JSON.stringify(items));window.dispatchEvent(new CustomEvent('forum:changed'));}
export function canInteract(role:UserRole){return ['ADMIN','TEACHER','STUDENT_FAMILY','STAFF'].includes(role)}
export function createPost(input:Pick<Post,'authorId'|'authorName'|'title'|'body'|'category'>){const item:Post={...input,id:crypto.randomUUID(),createdAt:new Date().toISOString(),reactions:0,reported:false,hidden:false,closed:false,comments:[]};save([item,...list()]);return item;}
export function addComment(postId:string,input:Pick<Comment,'authorId'|'authorName'|'body'>,parentId?:string){const items=list();const post=items.find(p=>p.id===postId);if(!post||post.closed||post.hidden)return false;const comment:Comment={...input,id:crypto.randomUUID(),createdAt:new Date().toISOString(),parentId,hidden:false};post.comments.push(comment);save(items);if(post.authorId!==input.authorId)notify({userId:post.authorId,type:'FORUM',title:'Nueva respuesta en el foro',message:`${input.authorName} comentó en “${post.title}”.`,path:'/forum',relatedId:postId});return true;}
export function react(postId:string){const items=list();const post=items.find(p=>p.id===postId);if(!post)return false;post.reactions+=1;save(items);return true;}
export function report(postId:string){const items=list();const post=items.find(p=>p.id===postId);if(!post)return false;post.reported=true;save(items);return true;}
export function moderate(postId:string,action:'hide'|'restore'|'close'|'reopen',role:UserRole){if(role!=='ADMIN')return false;const items=list();const post=items.find(p=>p.id===postId);if(!post)return false;if(action==='hide')post.hidden=true;if(action==='restore')post.hidden=false;if(action==='close')post.closed=true;if(action==='reopen')post.closed=false;save(items);return true;}
